backend:
  name: git-gateway
  branch: master

media_folder: static/images
public_folder: /images

collections:
  - label: "Pages"
    name: "pages"
    folder: "content/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    slug: "blog/{{slug}}"
    create: true
    fields:
      - { label: "Date", name: "date", widget: date }
      - { label: "Title", name: "title", widget: "string"  }
      - { label: "Body", name: "body", widget: "markdown" }
