backend:
  name: git-gateway
  branch: master

media_folder: static/images
public_folder: /images

collections:
  - label: "Page"
    name: "pages"
    folder: "content/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
    meta:
      - { label: 'SEO Description', name: 'description', widget: 'text' }
  - label: "Post"
    name: "posts"
    folder: "content/posts"
    slug: "{{slug}}"
    create: true
    fields:
      - {
          label: 'Publish Date',
          name: 'date',
          widget: 'date',
          dateFormat: 'MMMM DD YYYY',
          format: 'MMMM DD YYYY',
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image", required: false}
      - { label: "Body", name: "body", widget: "markdown" }
    meta:
      - { label: 'SEO Description', name: 'description', widget: 'text' }
