backend:
  name: git-gateway
  branch: master

media_folder: static/images
public_folder: /images

collections:
  - label: "Page"
    name: "pages"
    folder: "content/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - label: "Post"
    name: "posts"
    folder: "content/posts"
    create: true
    slug: "{{fields.slug}}"
    fields:
      - {
          label: 'Publish Date',
          name: 'date',
          widget: 'date',
          dateFormat: 'MMMM DD YYYY',
          format: 'MMMM DD YYYY',
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Featured Image", name: "image", widget: "image", required: false}
      - { label: "Category", name: "category", widget: "relation", collection: "categories", searchFields: ["title"], valueField: "title", displayFields: ["title"], required: false}
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }
  - label: 'Categories'
    name: 'categories'
    folder: "content/categories" 
    create: true
    slug: "{{slug}}"
    fields:
      - {label: Title, name: title, widget: string} 