backend:
  name: git-gateway
  branch: master

site_url: https://wabi-sabi.netlify.com/

media_folder: static/images
public_folder: /images

collections:
  - label: "Page"
    name: "pages"
    folder: "content/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
